//Category
export const GET_ALL_CATEGORIES = 'GET_ALL_CATEGORIES';


//News
export const CHANGE_CATEGORIES_NEW_NEWS = 'CHANGE_CATEGORIES_NEW_NEWS';
export const GET_INIT_CATEGORIES_NEW_NEWS = 'GET_INIT_CATEGORIES_NEW_NEWS';

