//Category
export const GET_ALL_CATEGORIES = "GET_ALL_CATEGORIES";
export const MENU_CATE_NEWS = "MENU_CATE_NEWS";
export const GET_CATEGORY_WITH_NEWS = "GET_CATEGORY_WITH_NEWS";

//News
export const CHANGE_CATEGORIES_NEW_NEWS = "CHANGE_CATEGORIES_NEW_NEWS";
export const GET_INIT_CATEGORIES_NEW_NEWS = "GET_INIT_CATEGORIES_NEW_NEWS";
export const RANDOM_LATEST_NEWS = "RANDOM_LATEST_NEWS";
export const HOT_NEWS_IN_WEEK = "HOT_NEWS_IN_WEEK";
export const FEATURE_NEWS = "FEATURE_NEWS";
export const FEATURE_NEWS_FOR_CATE = "FEATURE_NEWS_FOR_CATE";
export const NEWS_DETAIL = "NEWS_DETAIL";

//Tags
export const GET_RANDOM_TAGS = "GET_RANDOM_TAGS";
export const GET_TAG_WITH_NEWS = "GET_TAG_WITH_NEWS";
export const CLEAR_TAG_WITH_NEWS = "CLEAR_TAG_WITH_NEWS";

//Control
export const SEARCH_NEWS = "SEARCH_NEWS";
export const CLEAR_SEARCH_WITH_NEWS = "CLEAR_SEARCH_WITH_NEWS";
